/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_ABSTRACTZKIDRPCSERVER_H_
#define JSONRPC_CPP_STUB_ABSTRACTZKIDRPCSERVER_H_

#include <jsonrpccpp/server.h>

class AbstractZkidRPCServer : public jsonrpc::AbstractServer<AbstractZkidRPCServer>
{
  public:
    AbstractZkidRPCServer(jsonrpc::AbstractServerConnector &conn) : jsonrpc::AbstractServer<AbstractZkidRPCServer>(conn)
    {
        this->bindAndAddMethod(jsonrpc::Procedure("GenerateProofs", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT, "credential_descriptions", jsonrpc::JSON_ARRAY, NULL), &AbstractZkidRPCServer::GenerateProofsI);
    }

    inline virtual void GenerateProofsI(const Json::Value &request, Json::Value &response)
    {
        response = this->GenerateProofs(request["credential_descriptions"]);
    }
    virtual Json::Value GenerateProofs(const Json::Value &credential_descriptions) = 0;
};

#endif //JSONRPC_CPP_STUB_ABSTRACTZKIDRPCSERVER_H_
